export type {
  AnimationParams,
  TargetsParam,
  EasingParam,
  WAAPIEasingParam,
  Draggable,
  DraggableAxisParam,
  DraggableParams,
  WAAPIAnimationParams,
  DOMTargetsParam,
  DOMTargetSelector,
  AnimatableObject,
  AnimatableParams,
  ScrambleTextParams,
  TimelineParams,
  JSAnimation,
  Timer,
  TimerParams,
  TimerOptions,
  DrawableSVGGeometry,
  TextSplitterParams,
  SplitTemplateParams,
  FunctionValue,
  ScrollObserver,
  ScrollObserverParams,
  ScrollObserverAxisCallback,
  ScrollThresholdParam,
  ScrollThresholdValue,
  ScrollThresholdCallback,
} from 'animejs'

export type { AutoLayoutParams, LayoutAnimationParams } from 'animejs/layout'
