export type {
  AnimationParams,
  TargetsParam,
  EasingParam,
  WAAPIEasingParam,
  Draggable,
  DraggableAxisParam,
  DraggableParams,
  WAAPIAnimationParams,
  DOMTargetsParam,
  DOMTargetSelector,
  AnimatableObject,
  AnimatableParams,
  ScrambleTextParams,
  TimelineParams,
  JSAnimation,
  Timer,
  TimerParams,
  TimerOptions,
  DrawableSVGGeometry,
  TextSplitterParams,
  SplitTemplateParams,
} from 'animejs'
